name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout latest code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker Buildx (supports multi-stage builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4️⃣ Build and Push Docker image (uses your multi-stage Dockerfile)
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mydockerhubusername/react-nginx-app:latest
